const categories = [
  "Good vs Bad",
  "Highly addictive vs Mildly addictive",
  "Cold vs Hot",
  "Weird vs Normal",
  "Colorful vs Colorless",
  "High calorie vs Low calorie",
  "Feels good vs Feels bad",
  "Essential vs Inessential",
  "Expensive vs Cheap",
  "Overrated weapon vs Underrated weapon",
  "Common vs Rare",
  "Hard subject vs Easy subject",
  "Famous vs Unknown",
  "Easy to use vs Difficult to use",
  "Wired vs Tired",
  "Clean vs Dirty",
  "Requires skill vs Requires luck",
  "Flavorful vs Flavorless",
  "Fascinating topic vs Boring topic",
  "Good actor vs Bad actor",
  "Hipster vs Basic",
  "Safe job vs Dangerous job",
  "Sci-Fi vs Fantasy",
  "Formal vs Casual",
  "Overpaid vs Underpaid",
  "Wet vs Dry",
  "Overrated skill vs Underrated skill",
  "Encouraged vs Forbidden",
  "Happy song vs Sad song",
  "Durable vs Fragile",
  "Dork vs Geek",
  "Evil vs Good",
  "Best day of the year vs Worst day of the year",
  "Good habit vs Bad habit",
  "Dog person vs Cat person",
  "Openly love vs Guilty pleasure",
  "Talented vs Untalented",
  "Light vs Dark",
  "Overrated actor vs Underrated actor",
  "Easy to find vs Hard to find",
  "Beautiful man vs Ugly man",
  "Easy to remember vs Hard to remember",
  "Highbrow vs Lowbrow",
  "Healthy vs Unhealthy",
  "Good man vs Bad man",
  "Historically irrelevant vs Historically important",
  "Hairy vs Hairless",
  "Flexible vs Inflexible",
  "Exotic pet vs Normal pet",
  "Extrovert vs Introvert",
  "Movie was better vs Book was better",
  "Good movie vs Bad movie",
  "Beautiful vs Ugly",
  "Happens suddenly vs Happens slowly",
  "Career vs Job",
  "Hated vs Loved",
  "The Dark Side of the Force vs The Light Side of the Force",
  "Good pizza topping vs Bad pizza topping",
  "Utopia vs Dystopia",
  "Immature person vs Mature person",
  "Overrated thing to own vs Underrated thing to own",
  "Nice person vs Mean person",
  "Adventure movie vs Action movie"
];

function showRandomCategory() {
  const randomIndex = Math.floor(Math.random() * categories.length);
  document.getElementById("category").innerText = categories[randomIndex];
}

window.onload = showRandomCategory;
